pull_request_rules:
  - name: inform people about merge conflict
    conditions:
      - conflict
    actions:
      comment:
        message: 'Unfortunately it seems like some other contributions have been merged since you contributed. Please resolve those merge conflicts. For more info check out this page: https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line'
  - name: automatic merge 
    conditions:
      - -conflict
      - files=_data/requirements.json
    actions:
      merge:
        method: squash
        strict: true
  - name: add label for review for more than one file change
    conditions:
      - '#files>=2'
    actions:
      comment:
        message: 'This PR touches more than one file and has to be reviewed manually. @crystal-dawn'
      label:
        add:
          - 'needs-review'
